version: '3'
services: 
  cypress-tests:
    image: 'dhis2/cypress-tests:master'
    shm_size: '2gb' 
    environment:
      CYPRESS_BASE_URL: https://smoke.dhis2.org/dev_smoke
      CYPRESS_REPORT_PORTAL_ENABLED: ${REPORT_PORTAL_ENABLED:-'false'}
      CYPRESS_LOGIN_USERNAME: 'admin'
      CYPRESS_LOGIN_PASSWORD: 'district'
      CI_BUILD_ID: ${CI_BUILD_ID:-"test0002"}
      RP_TOKEN: ${RP_TOKEN}
      JIRA_ENABLED: ${JIRA_ENABLED}
      JIRA_USERNAME: ${JIRA_USERNAME}
      JIRA_PASSWORD: ${JIRA_PASSWORD}
      JIRA_RELEASE_VERSION_NAME: "${JIRA_RELEASE_VERSION_NAME}"
    volumes: 
      - ./allure-results:/usr/test/allure-results
      - ./allure-report:/usr/test/allure-report
      - ./screenshots:/usr/test/cypress/screenshots
    entrypoint: "npm run cy:parallel-report && python3 merge_launches.py"